---
- name: nfs1 | configure nfss
  hosts: server
  become: true 

  tasks:
  - name: install nfs
    shell: "{{item}}"
    with_items:
      - yum install -y nfs-utils
      - systemctl enable firewalld --now
      - firewall-cmd --add-service="nfs3" --add-service="rpc-bind"  --add-service="mountd" --permanent
      - firewall-cmd --reload
      - systemctl enable nfs --now
      - mkdir -p /srv/share/upload
      - chown -R nfsnobody:nfsnobody /srv/share
      - chmod 777 /srv/share/upload
      - echo "/srv/share 192.168.50.11/32(rw,sync,root_squash)" > /etc/exports
      - exportfs -r

- name: nfs2 | configure nfsc
  hosts: client
  become: true 

  tasks:
  - name: install nfs
    shell: "{{item}}"
    with_items:
      - yum install -y nfs-utils
      - systemctl enable firewalld --now
      - echo "192.168.50.10:/srv/share/ /mnt nfs vers=3,proto=udp 0 0" >> /etc/fstab
      - systemctl daemon-reload
      - systemctl restart remote-fs.target
      
